version: '2'
services:
postgres:
    image: postgres:9.6
    networks:
    - jenkins
    environment:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin
    volumes:
    - /var/postgres-data:/var/lib/postgresql/data
sonarqube:
    image: sonarqube
    ports:
    - "9000:9000"
    - "9092:9092"
    networks:
    - jenkins
    environment:
    SONARQUBE_JDBC_USERNAME: admin
    SONARQUBE_JDBC_PASSWORD: admin
    SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on: 
    - postgres

networks:
jenkins:
